### ISSUE TITLE
where can find the pre-trained model

### ISSUE THREAD

**Issue by huaxinxiao** [nameless-Chatoyant/PWC-Net_pytorch#2]
Hi @nameless-Chatoyant 
Where is the `models/best.pkl`?
Could you provide a pre-trained model for demo?
Thanks.

**Comment by nameless-Chatoyant** [comment]
Thanks for attention and sorry for there is no so called `best.pkl` yet...    
Network archetecture has been just updated, and previous pre-trained model is mismatching.    
It will cost about another 2-day to train and I will upload the model then.

**Comment by nameless-Chatoyant** [comment]
Hi @huaxinxiao

I have uploaded a model file which has a EPE of 6.5 on training set. (showed on tensorboard, averaged with prior higher EPE, so actual one is lower)

not the best model yet, hope it helps to explain the code:)

**Comment by huaxinxiao** [comment]
@nameless-Chatoyant  
Appreciate it. 
In demo script, it should be `--load examples/best.pkl`. :)

**Comment by nameless-Chatoyant** [comment]
Thanks~~ fixed it
