### ISSUE TITLE
Is it possible to provide pretrained model for KITTI 2015 as well?

### ISSUE THREAD

**Issue by sstamatis01** [nameless-Chatoyant/PWC-Net_pytorch#4]

**Comment by nameless-Chatoyant** [comment]
Hi @sstamatis01 

Thanks for attention! I'm just working on it~

As FlowNet2 says, scheduling datasets in the order of FlyingChairs -> FlyingThings3D -> KITTI/Sintel is better than training from scratch.

Previous models are all trained from scratch on SintelFinal, so I'm going to upload models for KITTI/Sintel in above scheduling way.

I have trained a model on FlyingChairs (about 200K iterations) and  is finetuning it on Sintel. After GPU is avaliable, I'll finetune it on KITTI. Of course, I'll upload all the models.

As for why I didn't firstly finetune on FlyingThings... It depends on when my bad network can download it for me :(

**Comment by sstamatis01** [comment]
Thanks for your reply, I ll wait and in the meantime try to train it on my own.
